### ISSUE TITLE
Google Play Warning

### ISSUE THREAD

**Issue by javis007** [yasirkula/UnityNativeGallery#185] opened 2021-04-28 02:02 UTC
Starting May 5th, you must explain to us why your app requires extensive storage access

We detected that your app contains the requestLegacyExternalStorage tag. This tag is included in the manifest file of one or more app bundles or APKs of the application.

If the developer’s application is suitable for devices with Android 11 or higher, the "partitioned storage" mechanism must be used so that users can better control access to their device storage space. Starting on May 5th, if you want to publish an app for Android 11 or higher, you must take one of the following measures:

Update your application to adopt best practices that pay more attention to privacy protection, such as using Storage Access Framework or Media Store API
Update your application, declare "All file access permissions" (MANAGE_EXTERNAL_STORAGE) in the manifest file, and complete the "All file access permissions" statement in the Play Management Center (from May 5)
Completely remove "all file access" from your app
For apps whose target platform is Android 11, the system will ignore the requestLegacyExternalStorage tag. To retain broad access rights, you must use "All file access rights".

If your app requests "all file access permissions", but this permission is not acceptable for use in your app, we will remove the app from Google Play and you will not be able to post updates.

How to do this?

**Comment by yasirkula** [comment] 2021-04-28 08:10
Duplicate of https://github.com/yasirkula/UnityNativeGallery/issues/182

**Closed by yasirkula** 2021-04-28 08:10 UTC
