### ISSUE TITLE
Photos Not getting saved.

### ISSUE THREAD

**Issue by JERINJACOBCHERIAN** [yasirkula/UnityNativeGallery#99] opened 2020-02-03 08:31 UTC
debug.Log("Permission result: " + NativeGallery.SaveImageToGallery(ss, "Boflora", "Image.png"));
debugText.text = "Permission result: " + NativeGallery.SaveImageToGallery(ss, "GalleryTest", "Image.png");

Hi I used to save images using the first line,but its not working not,but the second line is not working.When I try to change the name of the folder in the second line,thats isnt working either

**Comment by yasirkula** [comment] 2020-02-03 17:03
I'm a little confused, does the first line work or the second line work? Or neither? Are you testing on Android or iOS? Are there any meaningful error messages on logcat console or Xcode console?

**Comment by JERINJACOBCHERIAN** [comment] 2020-02-04 09:29
The second line works, the first one doesn't. Nothing in the console.I tried in android

I tried changing the name of the folder in the second line to the folder name in the first line, then the second line doesn't work either.

**Comment by yasirkula** [comment] 2020-02-04 09:45
Because Unity's console won't work, you must use logcat. If you'd like to see logcat logs in Unity editor, you can use this package: https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@0.1/manual/index.html. I'd expect an error message to show up in logcat for this issue.

Also please check out if the image shows up in gallery after restarting the device.

**Comment by JERINJACOBCHERIAN** [comment] 2020-02-04 11:00
using texture array is also permitted right?

    public Texture2D[] ss=new Texture2D[3];
    
public void userclickedsave()
    {
        StartCoroutine(ShowAndHide(1.0f)); // 1 second
        NativeGallery.Permission permission = NativeGallery.CheckPermission();
        NativeGallery.RequestPermission();
        if (permission == NativeGallery.Permission.Denied)
        {
            NativeGallery.OpenSettings();
        }

        else if (permission == NativeGallery.Permission.Granted)
        {
            // Save the screenshot to Gallery/Photos
            //Debug.Log("Permission result: " + NativeGallery.SaveImageToGallery(ss, "Boflora", "Image.png"));

            //debugText.text = "Permission result: " + NativeGallery.SaveImageToGallery(ss, "GalleryTest", "Image.png");
            debugText.text = "Permission result: " + NativeGallery.SaveImageToGallery(ss[i], "GalleryTest", "Image.png");

            //NativeGallery.SaveImageToGallery(ss[i], "Boflora", "Image.png");
            // To avoid memory leaks
            //Destroy(ss);

        }
        previewPanel.SetActive(false);

    }

**Comment by yasirkula** [comment] 2020-02-04 11:03
Yes arrays should work fine as long as the Texture at the specified index of the array exists.

**Comment by JERINJACOBCHERIAN** [comment] 2020-02-04 13:43
Hi,is there a limit of 32 pictures per folder? as it stopped adding new files once it hit 32 images(I am using the same name for saving every picture from my code).

Once I cleared some pictures,its adding now

**Comment by yasirkula** [comment] 2020-02-04 13:55
Not at all, this is the first time I hear about this issue. I've just now tested saving 64 images and it worked without any issues:

```csharp
private IEnumerator TakeScreenshotAndSave()
{
	yield return new WaitForEndOfFrame();

	Texture2D ss = new Texture2D( Screen.width, Screen.height, TextureFormat.RGB24, false );
	ss.ReadPixels( new Rect( 0, 0, Screen.width, Screen.height ), 0, 0 );
	ss.Apply();

	for( int i = 0; i < 64; i++ )
		Debug.Log( "Permission result: " + NativeGallery.SaveImageToGallery( ss, "Boflora", "My img.png" ) );
}
```

**Comment by JERINJACOBCHERIAN** [comment] 2020-02-05 07:07
Hi,

I used the same code you gave me and createad two folders(ran the same code twice). both folders finishes adding new images at 32

**Comment by yasirkula** [comment] 2020-02-05 17:06
I can't really tell. It might be a device specific issue. Please test the plugin on other devices to check if this is the case.

**Comment by umiringo** [comment] 2020-02-21 16:28
The same issue came to me too.
After debuging, I found that that's because after requestpermission, even I click grant the permission, but the checkpermission function will always return denied.
Did those part code has be changed?

**Comment by yasirkula** [comment] 2020-02-21 16:55
I don't think so: https://github.com/yasirkula/UnityNativeGallery/blame/master/JAR%20Source/NativeGalleryPermissionFragment.java. I'm sorry to say that I still don't know why some users experience this Denied issue, I can't spot any problematic lines in the code.

**Comment by umiringo** [comment] 2020-02-21 18:05
Hi, I think I found the solution by https://stackoverflow.com/questions/48172519/oreo-write-external-storage-permission

I add the tools:node="replace" to permission tag  and xmlns:tools="http://schemas.android.com/tools" to manifest tag
then the problem solved.

**Comment by yasirkula** [comment] 2020-02-21 18:12
Good to hear that there is a potential fix for this issue.

**Comment by yasirkula** [comment] 2020-10-01 12:29
32 image limit is probably caused by [this line](https://android.googlesource.com/platform/frameworks/base/+/oreo-release/core/java/android/os/FileUtils.java#618) in Android source code on Android 10+. I'll find a workaround but in the meantime, including timestamp in filename should resolve the issue ([example](https://forum.unity.com/threads/native-gallery-for-android-ios-open-source.519619/page-20#post-6364614)).

**Closed** 2020-10-06 14:56 UTC

**Comment by yasirkula** [comment] 2020-10-06 14:58
When 32 image limit is reached, NativeGallery will automatically append timestamp to the filename.
