### ISSUE TITLE
[IOS]  SaveImageToGallery saves as full black image

### ISSUE THREAD

**Issue by Archi97** [yasirkula/UnityNativeGallery#190] opened 2021-04-30 10:08 UTC
After taking screenshot and having it as Texture2D, Im trying to save it into gallery. 
But it is saving as full black image on IOS.  Android works perfect. 
Any idea why it is happening?

**Comment by yasirkula** [comment] 2021-04-30 11:35
Does the screenshot functionality of the [example code](https://github.com/yasirkula/UnityNativeGallery#example-code) suffer the same thing?

**Comment by Archi97** [comment] 2021-04-30 12:04
> Does the screenshot functionality of the [example code](https://github.com/yasirkula/UnityNativeGallery#example-code) suffer the same thing?

Yes, it is also saving full black.

**Comment by yasirkula** [comment] 2021-04-30 12:15
Hmm, can you reproduce the issue on a blank project using the example code, and on other iOS devices?

**Comment by Archi97** [comment] 2021-04-30 12:23
> Hmm, can you reproduce the issue on a fresh new project using the example code, and on other iOS devices?

It works in empty project. 
Hm. what can be the problem?

**Comment by yasirkula** [comment] 2021-04-30 12:25
If the logs don't provide any insight, then I'd recommend you to first synchronize empty project's Project Settings with the other project and see if the issue is related to a project setting. If it is, then it is a matter of toggling the project settings until the culprit is found. I unfortunately can't think of any reasons for this issue at the moment.

**Comment by Archi97** [comment] 2021-04-30 14:53
> and see if the issue

we found the issue.
We should uncheck Metal White-Only BackBuffering from Player settings ->Other settings.
Thanks you

**Comment by yasirkula** [comment] 2021-04-30 18:00
I see. Looks like it is an optimization option. If you'd like to keep it enabled, you can capture screenshots by rendering the camera to a RenderTexture and converting that RenderTexture to a Texture (screenshot). However, Screen Space - Overlay UI's won't show up in the screenshot and camera stacking won't be supported (these are limitation of this approach, not the plugin's limitations).

**Closed** 2021-06-23 08:54 UTC
Labels: bug
