### ISSUE TITLE
Missing assembly reference in Visual Studio and VS Code

### ISSUE THREAD

**Issue by Sov3rain** [yasirkula/UnityNativeGallery#146] opened 2020-10-23 14:21 UTC
**Description of the bug**

IDE is thinking that Native Gallery (same goes for Narive Share btw) is missing. Unity is not complaining by itself, and compilation is fine. But I can't get autocompletion to work and it's a pain.

**Reproduction steps**

It's the same both on VS Code and Visual studio.

**Platform specs**

- Unity version: 2020.1.8f1
- Platform: Windows 1909
- Device: Editor
- How did you download the plugin: Package Manager (up to date)

**Additional info**

![image](https://user-images.githubusercontent.com/10755450/97014808-1bea4300-154b-11eb-86a6-a40f19419946.png)

**Comment by yasirkula** [comment] 2020-10-23 14:43
I don't understand how NativeGallery would affect Visual Studio. It simply consists of a number of C# files. And it _works fine for me on VS Community 2019_ 😄

I'm closing this issue because it can either be a Unity bug or a Visual Studio bug. If, however, the issue is resolved after modifying NativeGallery's files in any way, please let me know.

And thank you for providing detailed information in this Issue.

**Closed by yasirkula** 2020-10-23 14:43 UTC
Labels: bug
