### ISSUE TITLE
android 

### ISSUE THREAD

**Issue by choigawoon** [yasirkula/UnityNativeGallery#285] opened 2023-04-11 00:47 UTC
**Description of the bug**

A clear and concise description of what the bug is. Before reporting a bug, please do a quick search in Issues to see if it is already reported. If the documentation has a FAQ (Frequently Asked Questions), please also check out the entries there.

even though i select denying permission for accessing gallery (image, video), nativegallery return granted and success to save file in Gallery.
i'm using 1.7.1 UnityNativeGallery

**Reproduction steps**

If possible, providing reproduction steps would be very helpful while pinpointing the issue. You can also post screenshots if you think they would be helpful.

1. call NativeGallery.RequestPermission
2. denied permission for accessing gallery (image, video)
3. even though i select denied, NativeGallery.RequestPermission return Granted.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2021.3.5f1
- Platform: Android
- Device: Galaxy Tab S7+
- How did you download the plugin: Asset Store

**Additional info**

Please check Logcat (Android) or Xcode console (iOS) for any meaningful error messages and include them here.

Android Version 13

**Comment by yasirkula** [comment] 2023-04-11 08:42
Duplicate of #183

**Closed by yasirkula** 2023-04-11 08:42 UTC
Labels: bug
