### ISSUE TITLE
Image not found error on some android devices

### ISSUE THREAD

**Issue by andpanda** [yasirkula/UnityNativeGallery#131] opened 2020-08-05 20:15 UTC
Hello there, first of all thank you very this wonderful plugin.
I have been using it for 2 years on android and iOs and everything is fine.

but lately I have found a problem, some Android devices are returning the path but when I try to load it it return Error 404 file not found.

I have tried it on my motog5 (32 bits) and it worked like a charm.
The path found: "file:///storage/emulated/0/Pictures/Screenshots/Screenshot_20200721-103920.png"

But I have tried now on my new Xiao mi redmi note 9 and when I try to load the image with WWW or UnityWebRequest the request throws a 404 file not found error.
Path:  "file:///storage/emulated/0/DCIM/Camera/IMG_20200803_003907.jpg"

The path that the API returns seems good, im grating the permissions, everything seems fine.
I am missing something?

Best Regards.

**Comment by yasirkula** [comment] 2020-08-05 20:24
Does NativeGallery.LoadImageAtPath suffer the same issue? If so, can you verify that the image file indeed exists at that path? What is your device's Android version?

**Comment by andpanda** [comment] 2020-08-05 20:34
I actually have found a solution to the problem.

Looks like we have to add the following on the manifest:
android:requestLegacyExternalStorage="true"

or else it will not work on Android 10.

Thank you very much for the fast response btw!

Found the solution here: https://github.com/bumptech/glide/issues/3896

**Comment by yasirkula** [comment] 2020-08-05 20:49
Hmm, I wonder why the image isn't automatically copied to a readable location using the following code: https://github.com/yasirkula/UnityNativeGallery/blob/a155ed0b9e12119bda929e65e416184907488fbf/.github/JAR%20Source/NativeGalleryMediaPickerFragment.java#L140-L141

Happy to hear that the issue is resolved, though.

**Comment by andpanda** [comment] 2020-08-05 21:51
This project is very old maybe the NativeGallery plugin is out dated!

**Comment by yasirkula** [comment] 2020-08-09 21:09
This issue is potentially fixed with the latest release: https://github.com/yasirkula/UnityNativeGallery/commit/84ac70d7e04088dbc166a58b5d26bbd5ea219170

**Closed by yasirkula** 2020-08-09 21:09 UTC
