### ISSUE TITLE
Incompatible pointer types on iOS

### ISSUE THREAD

**Issue by ivoras** [yasirkula/UnityNativeGallery#206] opened 2021-07-11 11:24 UTC
**Description of the bug**

While compiling the app with the plugin from the asset store, it bombs in Xcode with the error:

`Incompatible pointer types assigning to 'id<UINavigationControllerDelegate,UIImagePickerControllerDelegate> _Nullable' from 'Class'`

This is on line 120 of NativeCamera.mm

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *2021.1.14f1*
- Platform: *iOS*
- How did you download the plugin: *Asset store, plugin version 1.6.4*
- Xcode version: *Version 12.5.1 (12E507)*

**Additional info**

It did work with a previous version of Xcode :(

**Comment by yasirkula** [comment] 2021-07-11 12:27
Duplicate of https://github.com/yasirkula/UnityNativeGallery/issues/200. In short, you need to update the plugin via GitHub because Asset Store itself is buggy on that Unity version.

**Closed by yasirkula** 2021-07-11 12:27 UTC
Labels: bug
