### ISSUE TITLE
iOS 12 NSCocoaErrorDomain

### ISSUE THREAD

**Issue by yosun** [yasirkula/UnityNativeGallery#50] opened 2018-09-23 11:19 UTC
Have tried passing bytes and just the file path. (The file is definitely written to the internal path, juts not passing to photo gallery) Receive this error when trying to write to the photo gallery. 

Error creating asset: Error Domain=NSCocoaErrorDomain Code=-1 "(null)"

**Comment by yasirkula** [comment] 2018-09-23 19:50
Does the exact same code work on older iOS versions?

**Comment by magnetica** [comment] 2019-03-14 13:31
hi, I have the same problem with latest version.
can you help me?

**Comment by yasirkula** [comment] 2019-03-14 16:49
At the moment, I don't know the cause of this issue :/

**Comment by magnetica** [comment] 2019-03-16 09:21
I'm able to save a video but not a photo.
I supopsed the problem was related to the path.
in your documentation, you say the image is temporary stored in PersistentDataPath root.
I have my images in the same path.. so I moved all images in another folder.
I noticed the problem looking at console. you code printed "saving to pictures: xyz 1.jpg
my image was named xyz.jpg! bingo!
.... no, same error... 
after moving images in a folder, my file path is:
file:///var/mobile/Containers/Data/Application/145B82E9-68ED-42FF-A489-2E5E6F81F2B3/Documents/Images/FGFPHUQ8SF6F.jpg
you code say 
Saving to Pictures: FGFPHUQ8SF6F.jpg
Error creating asset: Error Domain=NSCocoaErrorDomain Code=-1 "(null)"

hope to help you to find the problem.

let me know

thanks

**Comment by yasirkula** [comment] 2019-10-09 20:37
Does the latest update somehow fix this issue, as well? https://github.com/yasirkula/UnityNativeGallery/commit/ba3fbf4f4c2840d6ac2c1e1145ca14b7834660c0

**Comment by FehrHassan** [comment] 2019-10-22 21:31
For me i still have the issue with the latest version downloaded and imported from unity asset store

Here is the error:
Saving to Pictures: Video
NativeGallery:SaveToGalleryInternal(String, String, MediaType, MediaSaveCallback)
NativeGallery:SaveToGallery(String, String, String, MediaType, MediaSaveCallback)
CameraCallback:Invoke(String)
NativeCameraNamespace.NCCameraCallbackiOS:OnMediaReceived(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

2019-10-22 23:26:25.793909+0200 Camera[2556:651850] [core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
2019-10-22 23:26:25.910066+0200 Camera[2556:652080] Error creating asset: Error Domain=PHPhotosErrorDomain Code=-1 "(null)"
The Error in saving the file: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)
MediaSaveCallback:Invoke(String)
NativeGalleryNamespace.NGMediaSaveCallbackiOS:OnMediaSaveFailed(String)

**Comment by yasirkula** [comment] 2019-10-23 17:23
Does your video file have an extension? If not, can you try adding the file extension to your video?

**Comment by FehrHassan** [comment] 2019-10-23 18:03
I am actually use your library NativeCamera to record the video and after recording the video, i want to save it in the photos
Here is the RecordVideo() function
```
private void RecordVideo() {
        NativeCamera.Permission permission = NativeCamera.RecordVideo((path) => {
            Debug.Log("Video path: " + path);
            if (path != null) {
                // Play the recorded video
                //Handheld.PlayFullScreenMovie("file://" + path);

                NativeGallery.SaveVideoToGallery(existingMediaPath: path, album: "Fehr", filename: "Video", callback);
            }
        }, NativeCamera.Quality.Default, 5);
        Debug.Log("Permission result: " + permission);
    }

    private void callback(string error) {
        Debug.Log("The Error in saving the file: " + error);
    }
```

**Comment by yasirkula** [comment] 2019-10-24 00:06
Can you try adding these lines above SaveVideoToGallery:

```csharp
System.IO.File.Move(path, path + ".mov");
path += ".mov";
```

I am just wondering if adding an extension to the file will resolve the issue. If so, I'll see what can be done about this NativeCamera issue.

**Comment by FehrHassan** [comment] 2019-10-24 00:36
Actually, it doesn't work and the extension is repeated in the path :(

Here is the logs from xcode

Permission result: Granted
MyScript:RecordVideo()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

2019-10-24 02:28:56.793206+0200 Camera[3678:1063353] [Common] _BSMachError: port 12703; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2019-10-24 02:28:56.794856+0200 Camera[3678:1063353] [Common] _BSMachError: port 12703; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
-> applicationWillResignActive()
WARNING -> applicationDidReceiveMemoryWarning()
-> applicationDidBecomeActive()
2019-10-24 02:31:02.503785+0200 Camera[3678:1063353] libMobileGestalt MobileGestalt.c:3154: statfs(/mnt4): No such file or directory
Video path: /private/var/mobile/Containers/Data/Application/4E03A1EA-7CAD-437C-B9E1-8160F1E80BD0/tmp/59356986249__B6DBA626-CC01-47D8-850E-BCCBEF83FFFD.MOV
MyScript:<RecordVideo>b__3_0(String)
CameraCallback:Invoke(String)
NativeCameraNamespace.NCCameraCallbackiOS:OnMediaReceived(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

The path is: /private/var/mobile/Containers/Data/Application/4E03A1EA-7CAD-437C-B9E1-8160F1E80BD0/tmp/59356986249__B6DBA626-CC01-47D8-850E-BCCBEF83FFFD.MOV
MyScript:<RecordVideo>b__3_0(String)
CameraCallback:Invoke(String)
NativeCameraNamespace.NCCameraCallbackiOS:OnMediaReceived(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

The path is 2: /private/var/mobile/Containers/Data/Application/4E03A1EA-7CAD-437C-B9E1-8160F1E80BD0/tmp/59356986249__B6DBA626-CC01-47D8-850E-BCCBEF83FFFD.MOV.mov
MyScript:<RecordVideo>b__3_0(String)
CameraCallback:Invoke(String)
NativeCameraNamespace.NCCameraCallbackiOS:OnMediaReceived(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Saving to Pictures: Video
NativeGallery:SaveToGalleryInternal(String, String, MediaType, MediaSaveCallback)
NativeGallery:SaveToGallery(String, String, String, MediaType, MediaSaveCallback)
CameraCallback:Invoke(String)
NativeCameraNamespace.NCCameraCallbackiOS:OnMediaReceived(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

2019-10-24 02:31:29.679463+0200 Camera[3678:1063353] [core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
2019-10-24 02:31:29.688925+0200 Camera[3678:1063353] [Common] _BSMachError: port fb1b; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2019-10-24 02:31:29.690767+0200 Camera[3678:1063353] [Common] _BSMachError: port fb1b; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
-> applicationWillResignActive()
2019-10-24 02:31:29.794322+0200 Camera[3678:1063516] Error creating asset: Error Domain=PHPhotosErrorDomain Code=-1 "(null)"
-> applicationDidBecomeActive()
The Error in saving the file: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)
MediaSaveCallback:Invoke(String)
NativeGalleryNamespace.NGMediaSaveCallbackiOS:OnMediaSaveFailed(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)


and here is my modified code
```
private void RecordVideo() {
        NativeCamera.Permission permission = NativeCamera.RecordVideo((path) => {
            Debug.Log("Video path: " + path);
            if (path != null) {
                // Play the recorded video
                //Handheld.PlayFullScreenMovie("file://" + path);
                System.IO.File.Move(path, path + ".mov");
                Debug.Log("The path is: " + path);
                path += ".mov";
                Debug.Log("The path is 2: " + path);

                NativeGallery.SaveVideoToGallery(existingMediaPath: path, album: "Fehr", filename: "Video", callback);
            }
        }, NativeCamera.Quality.Default, 5);
        Debug.Log("Permission result: " + permission);
    }

    private void callback(string error) {
        Debug.Log("The Error in saving the file: " + error);
    }
```

**Comment by yasirkula** [comment] 2019-10-24 16:28
Can you change `filename: "Video"` to `filename: "Video.mov"`?

**Comment by FehrHassan** [comment] 2019-10-24 23:27
Thank you very much for your help
Now it is working for me, actually i have to change the from ```filename :"video"``` to ```filename: "Video.mov"```
Thanks a lot

**Comment by yasirkula** [comment] 2020-04-06 18:47
Closing this Issue since https://github.com/yasirkula/UnityNativeGallery/commit/ba3fbf4f4c2840d6ac2c1e1145ca14b7834660c0 has potentially resolved it. Please reopen the Issue if the problem is still there.

**Closed by yasirkula** 2020-04-06 18:47 UTC
