### ISSUE TITLE
The file couldn’t be opened because you don’t have permission to view it.

### ISSUE THREAD

**Issue by yosun** [yasirkula/UnityNativeGallery#189] opened 2021-04-30 00:16 UTC
**Description of the bug**

When an image is picked and passed to app this error occurs

[default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }

**Reproduction steps**

If possible, providing reproduction steps would be very helpful while pinpointing the issue. You can also post screenshots if you think they would be helpful.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2020.3.0f1*
- Platform: *e.g. iOS*
- Device: *iPhone 12 Pro Max ioO 14.4*
- How did you download the plugin: *unitypackage from this repo*

**Comment by yasirkula** [comment] 2021-04-30 08:38
Duplicate of https://github.com/yasirkula/UnityNativeGallery/issues/143

**Closed by yasirkula** 2021-04-30 08:38 UTC
Labels: bug
