### ISSUE TITLE
iOS 13, loaded image remove alpha information

### ISSUE THREAD

**Issue by loveguan91** [yasirkula/UnityNativeGallery#105] opened 2020-03-08 02:58 UTC
It seems that in the latest update, when loading images from gallery, the png files will lost their alpha information, turn into white pixels. Maybe they are converted to jpg format?

**Comment by loveguan91** [comment] 2020-03-08 04:02
After investigation, the raw "PNG" image, after pick up, in temp path, changed into "JPEG" format. So alpha information is lost.

**Comment by brad3d** [comment] 2020-03-08 16:35
adding a +1 to this one. Same issue here.

**Comment by yasirkula** [comment] 2020-03-08 17:12
I can't really see any issues in the [native code](https://github.com/yasirkula/UnityNativeGallery/blob/8c8139ac393d226144ff26d4cde9ca7f6d687ba7/Plugins/NativeGallery/iOS/NativeGallery.mm#L508-L562). What is the [latest release](https://github.com/yasirkula/UnityNativeGallery/releases) that doesn't have this issue?

**Comment by loveguan91** [comment] 2020-03-09 02:53
I retried the code from my repository, and attached the code here. Please help to check.
1. Client code call: NativeGallery.GetImageFromGallery, choose a png file with alpha.
2. In the callback, the path turn into "jpeg" extension.
3. This error only happened on iOS, Android works fine.
4. Switch to the attached version, everything works fine./Users/wangwei/Temporary/Assets/Plugins/NativeGallery

**Comment by yasirkula** [comment] 2020-03-09 17:37
It looks like until I run some tests myself, I won't be able to pinpoint the issue. I don't have access to a Mac workstation, so unfortunately it will take some time. In the meantime, you can continue using the version you have.

**Comment by loveguan91** [comment] 2020-03-10 12:46
> It looks like until I run some tests myself, I won't be able to pinpoint the issue. I don't have access to a Mac workstation, so unfortunately it will take some time. In the meantime, you can continue using the version you have.

Update: the latest version code works correctly on iOS 12, it seems that this is iOS 13’s bug. The selected image’s name is “Public.jpeg” forever.

**Comment by yasirkula** [comment] 2020-04-06 19:39
## Notes to self

Possible bugfix: https://medium.com/@SDxBacon/ios-13-missing-png-transparent-background-issue-500627d5fe50

The recommended solution is to change this value to PHImageRequestOptionsVersionOriginal: https://github.com/yasirkula/UnityNativeGallery/blob/cd613167c961087bc1e553310806c072e2267dca/Plugins/NativeGallery/iOS/NativeGallery.mm#L525

But any edits made by the user won't be visible in the returned image, so this solution comes with its own issues.

Perhaps a better solution would be to detect if a png image was picked but then got converted into jpeg when calling requestImageDataAndOrientationForAsset.

Also, maybe the new "_Optimize iPhone Storage_" control in the Photos settings is related to this issue?

**Comment by yasirkula** [comment] 2020-04-07 19:29
@loveguan91 @brad3d Inside NativeGallery.mm, could you try changing the `imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo` function as follows:

```objc
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
+ (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {
	resultPath = nil;
	
	if ([info[UIImagePickerControllerMediaType] isEqualToString:(NSString *)kUTTypeImage]) { // image picked
		// On iOS 8.0 or later, try to obtain the raw data of the image (which allows picking gifs properly or preserving metadata)
		if ([[[UIDevice currentDevice] systemVersion] compare:@"8.0" options:NSNumericSearch] != NSOrderedAscending) {
			PHAsset *asset = nil;
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
			if ([[[UIDevice currentDevice] systemVersion] compare:@"11.0" options:NSNumericSearch] != NSOrderedAscending) {
				// Try fetching the source image via UIImagePickerControllerImageURL
				NSURL *mediaUrl = info[UIImagePickerControllerImageURL];
				if (mediaUrl != nil) {
					NSString *imagePath = [mediaUrl path];
					if (imagePath != nil && [[NSFileManager defaultManager] fileExistsAtPath:imagePath]) {
						NSError *error;
						NSString *newPath = [pickedMediaSavePath stringByAppendingPathExtension:[imagePath pathExtension]];
						
						if (![[NSFileManager defaultManager] fileExistsAtPath:newPath] || [[NSFileManager defaultManager] removeItemAtPath:newPath error:&error]) {
							if ([[NSFileManager defaultManager] copyItemAtPath:imagePath toPath:newPath error:&error]) {
								resultPath = newPath;
								NSLog(@"Copied source image from UIImagePickerControllerImageURL");
							}
							else
								NSLog(@"Error copying image: %@", error);
						}
						else
							NSLog(@"Error deleting existing image: %@", error);
					}
				}
				
				if (resultPath == nil)
					asset = info[UIImagePickerControllerPHAsset];
			}
#endif
			
			if (resultPath == nil) {
				NSLog(@"===1111111111==========: %@", info);
				
				if (asset == nil) {
					NSURL *mediaUrl = info[UIImagePickerControllerReferenceURL] ?: info[UIImagePickerControllerMediaURL];
					if (mediaUrl != nil)
						asset = [[PHAsset fetchAssetsWithALAssetURLs:[NSArray arrayWithObject:mediaUrl] options:nil] firstObject];
				}
				
				if (asset != nil) {
					PHImageRequestOptions *options = [[PHImageRequestOptions alloc] init];
					options.synchronous = YES;
					options.version = PHImageRequestOptionsVersionCurrent;
					
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000
					if ([[[UIDevice currentDevice] systemVersion] compare:@"13.0" options:NSNumericSearch] != NSOrderedAscending) {
						[[PHImageManager defaultManager] requestImageDataAndOrientationForAsset:asset options:options resultHandler:^(NSData *imageData, NSString *dataUTI, CGImagePropertyOrientation orientation, NSDictionary *imageInfo) {
							if (imageData != nil)
							{
								NSLog(@"===2222222222============: %@", imageInfo);
								[self trySaveSourceImage:imageData withInfo:imageInfo];
							}
							else
								NSLog(@"Couldn't fetch raw image data");
						}];
					}
					else {
#endif
						[[PHImageManager defaultManager] requestImageDataForAsset:asset options:options resultHandler:^(NSData *imageData, NSString *dataUTI, UIImageOrientation orientation, NSDictionary *imageInfo) {
							if (imageData != nil)
								[self trySaveSourceImage:imageData withInfo:imageInfo];
							else
								NSLog(@"Couldn't fetch raw image data");
						}];
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000
					}
#endif
				}
			}
		}
		
		if (resultPath == nil) {
			// Temporarily save image as PNG
			UIImage *image = info[UIImagePickerControllerOriginalImage];
			if (image != nil) {
				resultPath = [pickedMediaSavePath stringByAppendingPathExtension:@"png"];
				if (![UIImagePNGRepresentation(image) writeToFile:resultPath atomically:YES]) {
					NSLog(@"Error creating PNG image");
					resultPath = nil;
				}
			}
			else
				NSLog(@"Error fetching original image from picker");
		}
	}
	else { // video picked
		NSURL *mediaUrl = info[UIImagePickerControllerMediaURL] ?: info[UIImagePickerControllerReferenceURL];
		if (mediaUrl != nil) {
			resultPath = [mediaUrl path];
			
			// On iOS 13, picked file becomes unreachable as soon as the UIImagePickerController disappears,
			// in that case, copy the video to a temporary location
			if ([[[UIDevice currentDevice] systemVersion] compare:@"13.0" options:NSNumericSearch] != NSOrderedAscending) {
				NSError *error;
				NSString *newPath = [pickedMediaSavePath stringByAppendingPathExtension:[resultPath pathExtension]];
				
				if (![[NSFileManager defaultManager] fileExistsAtPath:newPath] || [[NSFileManager defaultManager] removeItemAtPath:newPath error:&error]) {
					if ([[NSFileManager defaultManager] copyItemAtPath:resultPath toPath:newPath error:&error])
						resultPath = newPath;
					else {
						NSLog(@"Error copying video: %@", error);
						resultPath = nil;
					}
				}
				else {
					NSLog(@"Error deleting existing video: %@", error);
					resultPath = nil;
				}
			}
		}
	}
	
	popup = nil;
	imagePicker = nil;
	imagePickerState = 2;
	UnitySendMessage("NGMediaReceiveCallbackiOS", "OnMediaReceived", [self getCString:resultPath]);
	
	[picker dismissViewControllerAnimated:NO completion:nil];
}
#pragma clang diagnostic pop
```

I'm trying to copy the image file directly from UIImagePickerControllerImageURL. If it still has the jpeg issue, could you verify that the picked image does have transparency? Perhaps, if the image was edited, its transparency was lost while saving the image?

If it doesn't work, I believe changing the following value to PHImageRequestOptionsVersionOriginal resolved the issue, am I right (though, this time, any edits made to the image in Photos won't be reflected to the generated Texture2D): https://github.com/yasirkula/UnityNativeGallery/blob/cd613167c961087bc1e553310806c072e2267dca/Plugins/NativeGallery/iOS/NativeGallery.mm#L525

P.S. I couldn't reproduce this issue on an iPad running iOS 13, so I need your help to figure out a fix for this issue.

**Comment by loveguan91** [comment] 2020-04-22 13:15
@yasirkula 
Sorry for my late response.
I tested the latest code on iOS 13, it works correct now.
Thank you for your hard work.

**Closed** 2020-04-22 14:06 UTC
