### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by freecandoall** [yasirkula/UnityNativeGallery#283] opened 2023-03-08 08:06 UTC
Undefined symbols for architecture arm64 error while proceeding Unity ios build with teamcity. Please help.

- Unity version: 2022.1.23f1*
- OSX version: Ventura 13.0
- XCode version: 14.2 (14C18)

 

Undefined symbols for architecture arm64:
[11:21:40 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60778&logView=flowAware&linesState=60778)    "_OBJC_CLASS_$_PHPickerConfiguration", referenced from:
[11:21:40 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60779&logView=flowAware&linesState=60779)        objc-class-ref in NativeGallery.o
[11:21:41 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60780&logView=flowAware&linesState=60780)    "_OBJC_CLASS_$_PHPickerFilter", referenced from:
[11:21:41 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60781&logView=flowAware&linesState=60781)        objc-class-ref in NativeGallery.o
[11:21:41 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60782&logView=flowAware&linesState=60782)    "_OBJC_CLASS_$_PHPickerViewController", referenced from:
[11:21:41 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60783&logView=flowAware&linesState=60783)        objc-class-ref in NativeGallery.o
[11:21:41 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60784&logView=flowAware&linesState=60784)    "_UTTypeConformsTo", referenced from:
[11:21:41 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60785&logView=flowAware&linesState=60785)        +[UNativeGallery getMediaTypeFromExtension:] in NativeGallery.o
[11:21:42 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60786&logView=flowAware&linesState=60786)    "_UTTypeCreatePreferredIdentifierForTag", referenced from:
[11:21:42 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60787&logView=flowAware&linesState=60787)        +[UNativeGallery getMediaTypeFromExtension:] in NativeGallery.o
[11:21:42 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60788&logView=flowAware&linesState=60788)    "_kUTTagClassFilenameExtension", referenced from:
[11:21:42 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60789&logView=flowAware&linesState=60789)        +[UNativeGallery getMediaTypeFromExtension:] in NativeGallery.o
[11:21:42 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60790&logView=flowAware&linesState=60790)    "_kUTTypeAudio", referenced from:
[11:21:42 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60791&logView=flowAware&linesState=60791)        +[UNativeGallery getMediaTypeFromExtension:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60792&logView=flowAware&linesState=60792)    "_kUTTypeImage", referenced from:
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60793&logView=flowAware&linesState=60793)        +[UNativeCamera openCamera:defaultCamera:savePath:maxImageSize:videoQuality:maxVideoDuration:] in NativeCamera.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60794&logView=flowAware&linesState=60794)        +[UNativeCamera imagePickerController:didFinishPickingMediaWithInfo:] in NativeCamera.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60795&logView=flowAware&linesState=60795)        +[UNativeGallery pickMedia:savePath:permissionFreeMode:selectionLimit:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60796&logView=flowAware&linesState=60796)        +[UNativeGallery imagePickerController:didFinishPickingMediaWithInfo:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60797&logView=flowAware&linesState=60797)        +[UNativeGallery picker:didFinishPicking:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60798&logView=flowAware&linesState=60798)        +[UNativeGallery getMediaTypeFromExtension:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60799&logView=flowAware&linesState=60799)    "_kUTTypeLivePhoto", referenced from:
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60800&logView=flowAware&linesState=60800)        +[UNativeGallery pickMedia:savePath:permissionFreeMode:selectionLimit:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60801&logView=flowAware&linesState=60801)        +[UNativeGallery imagePickerController:didFinishPickingMediaWithInfo:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60802&logView=flowAware&linesState=60802)        +[UNativeGallery picker:didFinishPicking:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60803&logView=flowAware&linesState=60803)        +[UNativeGallery getMediaTypeFromExtension:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60804&logView=flowAware&linesState=60804)    "_kUTTypeMovie", referenced from:
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60805&logView=flowAware&linesState=60805)        +[UNativeCamera openCamera:defaultCamera:savePath:maxImageSize:videoQuality:maxVideoDuration:] in NativeCamera.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60806&logView=flowAware&linesState=60806)        +[UNativeGallery pickMedia:savePath:permissionFreeMode:selectionLimit:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60807&logView=flowAware&linesState=60807)        +[UNativeGallery picker:didFinishPicking:] in NativeGallery.o
[11:21:43 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60808&logView=flowAware&linesState=60808)        +[UNativeGallery getMediaTypeFromExtension:] in NativeGallery.o
[11:21:44 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60809&logView=flowAware&linesState=60809)    "_kUTTypeVideo", referenced from:
[11:21:44 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60810&logView=flowAware&linesState=60810)        +[UNativeGallery pickMedia:savePath:permissionFreeMode:selectionLimit:] in NativeGallery.o
[11:21:44 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60811&logView=flowAware&linesState=60811)        +[UNativeGallery picker:didFinishPicking:] in NativeGallery.o
[11:21:44 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60812&logView=flowAware&linesState=60812)        +[UNativeGallery getMediaTypeFromExtension:] in NativeGallery.o
[11:21:44 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60813&logView=flowAware&linesState=60813)  ld: symbol(s) not found for architecture arm64
[11:21:44 ](http://192.168.77.124:8111/buildConfiguration/Colorverse_Dev_DevIOS/11248?buildTab=log&focusLine=60814&logView=flowAware&linesState=60814)  clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yasirkula** [comment] 2023-03-08 13:25
Duplicate of #199   #207   #252

**Closed by yasirkula** 2023-03-08 13:25 UTC
Labels: bug
