### ISSUE TITLE
NativeGallery.jar source code

### ISSUE THREAD

**Issue by PavelDoGreat** [yasirkula/UnityNativeGallery#119] opened 2020-05-08 11:08 UTC
Hi, thank you for creating this plugin. Title says it all, is there source code for NativeGallery.jar? There is a bug on Android that doesn't allow saving more than 32 images to one album. I want to look into it and fix it. It would be very cool from you to provide the source code.

**Comment by yasirkula** [comment] 2020-05-08 12:07
It is related to [this issue](https://github.com/yasirkula/UnityNativeGallery/issues/99#issuecomment-581915279) then. JAR source code is available at: https://github.com/yasirkula/UnityNativeGallery/tree/master/.github/JAR%20Source. Please share your findings and any relevant sources (e.g. stackoverflow entries) here.

**Comment by yasirkula** [comment] 2020-09-12 11:15
Duplicate of #99

**Closed by yasirkula** 2020-09-12 11:15 UTC
